/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRINCIPAL;

import UTILIDA.CONEXAO;
import UTILIDA.GRA_ALT_EXC;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrezza
 */
public class LIMITE extends javax.swing.JDialog {
    CONEXAO CONEXAO = new CONEXAO();
    
    /**
     * Creates new form LIMITE
     */
    public LIMITE(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        CONEXAO.conecta();
        MOSTRA_DADOS_LIMITE();
        Cod.setVisible(false);
        Cod.setBackground(Color.MAGENTA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Cod = new javax.swing.JLabel();
        Cor = new javax.swing.JLabel();
        Limite = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SpinLIMITE = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(Color.WHITE);
        setResizable(false);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Cod.setText("Cod");
        jLayeredPane1.add(Cod);
        Cod.setBounds(350, 10, 40, 20);

        Cor.setBackground(new java.awt.Color(255, 0, 102));
        Cor.setOpaque(true);
        jLayeredPane1.add(Cor);
        Cor.setBounds(360, 110, 30, 20);
        jLayeredPane1.add(Limite);
        Limite.setBounds(60, 20, 190, 30);

        jLabel1.setText("Limite:");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(10, 20, 40, 30);

        SpinLIMITE.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinLIMITEStateChanged(evt);
            }
        });
        jLayeredPane1.add(SpinLIMITE);
        SpinLIMITE.setBounds(250, 20, 20, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/verificar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(290, 20, 30, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Quando a quantidade exceder ao limite de agendamento, \no dia no calendário será destacado na cor \"MAGENTA\".");
        jScrollPane1.setViewportView(jTextArea1);

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 56, 310, 80);

        jLabel2.setText("Cor:");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(330, 110, 30, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SpinLIMITEStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinLIMITEStateChanged
        try {
            int L = Integer.parseInt(Limite.getText());
            int JS = Integer.parseInt(SpinLIMITE.getValue().toString());
            if(JS == 1) {
                L = L + 1;
            }
            if(JS == -1 & L > 0){
                L = L-1;
            }
            
            Limite.setText(""+L);
            SpinLIMITE.setValue(0);
            
        } catch (Exception erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_SpinLIMITEStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Alteracao();
            ECRAPRIN.MOSTRA_DADOS_LIMITE();
            ECRAPRIN.LEGENDA();
            ECRAPRIN.INSERE_COR_CALENDARIO();
        } catch (Exception erro) {
            System.out.println(erro);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LIMITE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LIMITE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LIMITE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LIMITE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LIMITE dialog = new LIMITE(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cod;
    private javax.swing.JLabel Cor;
    private javax.swing.JTextField Limite;
    private javax.swing.JSpinner SpinLIMITE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables


    private PRINCIPAL ECRAPRIN;

    public void MostraLimite(PRINCIPAL MostraLimit){
        this.ECRAPRIN = MostraLimit;
        setVisible(true);
    }
    
    public void MOSTRA_DADOS_LIMITE() {
        try {
            CONEXAO.executaSQL("select * from configuracao");
            CONEXAO.resultset.first();
            Cod.setText(CONEXAO.resultset.getString("cod"));
            Limite.setText(CONEXAO.resultset.getString("limiteagendamento"));
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro" + erro);
    }
    
    }
public void Alteracao() throws IOException { // VAI UTILIZAR O METODO DO BANCO DE DADOS ALTERAR
        String[] coluna = {"limiteagendamento"};
        String[] valor = {Limite.getText()};
        String tabela = "configuracao";
        String condicao = " WHERE cod = " + Cod.getText();

        GRA_ALT_EXC altera = new GRA_ALT_EXC();
        altera.ALTERA(coluna, valor, tabela, condicao);
    
    }

}
