/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRINCIPAL;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Andrezza p/ Smart Level
 */
public class PRINCIPAL extends javax.swing.JFrame {
    
    int AnoFIXO = 0, MesFIXO = 0, DiaFIXO = 0; //informaçóes sobre as variaveis
    int AnoAltera = 0, MesAltera = 0, DiaAltera = 0;
    int valorselecao = 0;
    /**
     * Creates new form PRINCIPAL
     */
    public PRINCIPAL() {
        initComponents();
        INICIACALENDARIO();
        CALENDARIO();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        SelecaoMes = new javax.swing.JComboBox<>();
        SelecaoAno = new javax.swing.JComboBox();
        ls1 = new javax.swing.JLabel();
        ls2 = new javax.swing.JLabel();
        ls3 = new javax.swing.JLabel();
        ls4 = new javax.swing.JLabel();
        ls5 = new javax.swing.JLabel();
        ls6 = new javax.swing.JLabel();
        t7 = new javax.swing.JLabel();
        t14 = new javax.swing.JLabel();
        t21 = new javax.swing.JLabel();
        t28 = new javax.swing.JLabel();
        t35 = new javax.swing.JLabel();
        ls7 = new javax.swing.JLabel();
        t42 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        t13 = new javax.swing.JLabel();
        t20 = new javax.swing.JLabel();
        t27 = new javax.swing.JLabel();
        t34 = new javax.swing.JLabel();
        t41 = new javax.swing.JLabel();
        t5 = new javax.swing.JLabel();
        t12 = new javax.swing.JLabel();
        t19 = new javax.swing.JLabel();
        t26 = new javax.swing.JLabel();
        t33 = new javax.swing.JLabel();
        t40 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        t11 = new javax.swing.JLabel();
        t18 = new javax.swing.JLabel();
        t25 = new javax.swing.JLabel();
        t32 = new javax.swing.JLabel();
        t39 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t10 = new javax.swing.JLabel();
        t17 = new javax.swing.JLabel();
        t24 = new javax.swing.JLabel();
        t31 = new javax.swing.JLabel();
        t38 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t9 = new javax.swing.JLabel();
        t16 = new javax.swing.JLabel();
        t23 = new javax.swing.JLabel();
        t30 = new javax.swing.JLabel();
        t37 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        t8 = new javax.swing.JLabel();
        t15 = new javax.swing.JLabel();
        t22 = new javax.swing.JLabel();
        t29 = new javax.swing.JLabel();
        t36 = new javax.swing.JLabel();
        VoltarDataInicial = new javax.swing.JButton();
        AnoPagina1 = new javax.swing.JLabel();
        AnoPagina2 = new javax.swing.JLabel();
        SemanaPagina1 = new javax.swing.JLabel();
        DiaPagina1 = new javax.swing.JLabel();
        MesPagina1 = new javax.swing.JLabel();
        SemanaPagina2 = new javax.swing.JLabel();
        DiaPagina2 = new javax.swing.JLabel();
        MesPagina2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SelecaoMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        SelecaoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecaoMesActionPerformed(evt);
            }
        });

        SelecaoAno.setEditable(true);
        SelecaoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecaoAnoActionPerformed(evt);
            }
        });

        ls1.setBackground(new java.awt.Color(0, 204, 204));
        ls1.setForeground(new java.awt.Color(255, 0, 51));
        ls1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ls1.setText("Dom");
        ls1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        ls2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ls2.setText("Seg");
        ls2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        ls3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ls3.setText("Ter");
        ls3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        ls4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ls4.setText("Qua");
        ls4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        ls5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ls5.setText("Qui");
        ls5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        ls6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ls6.setText("Sex");
        ls6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        t7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t7.setText("0");

        t14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t14.setText("0");

        t21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t21.setText("0");

        t28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t28.setText("0");

        t35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t35.setText("0");

        ls7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ls7.setText("Sab");
        ls7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        t42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t42.setText("0");

        t6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t6.setText("0");

        t13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t13.setText("0");

        t20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t20.setText("0");

        t27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t27.setText("0");

        t34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t34.setText("0");

        t41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t41.setText("0");

        t5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t5.setText("0");

        t12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t12.setText("0");

        t19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t19.setText("0");

        t26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t26.setText("0");

        t33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t33.setText("0");

        t40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t40.setText("0");

        t4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t4.setText("0");

        t11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t11.setText("0");

        t18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t18.setText("0");

        t25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t25.setText("0");

        t32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t32.setText("0");

        t39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t39.setText("0");

        t3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t3.setText("0");

        t10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t10.setText("0");

        t17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t17.setText("0");

        t24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t24.setText("0");

        t31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t31.setText("0");

        t38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t38.setText("0");

        t2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t2.setText("0");

        t9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t9.setText("0");

        t16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t16.setText("0");

        t23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t23.setText("0");

        t30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t30.setText("0");

        t37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t37.setText("0");

        t1.setForeground(new java.awt.Color(255, 0, 51));
        t1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t1.setText("0");

        t8.setForeground(new java.awt.Color(255, 0, 51));
        t8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t8.setText("0");

        t15.setForeground(new java.awt.Color(255, 0, 51));
        t15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t15.setText("0");

        t22.setForeground(new java.awt.Color(255, 0, 51));
        t22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t22.setText("0");

        t29.setForeground(new java.awt.Color(255, 0, 51));
        t29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t29.setText("0");

        t36.setForeground(new java.awt.Color(255, 0, 51));
        t36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t36.setText("0");

        jLayeredPane2.setLayer(SelecaoMes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(SelecaoAno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ls1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ls2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ls3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ls4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ls5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ls6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ls7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t42, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(t36, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(t1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t30, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(t2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(t3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(t4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(ls1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ls2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ls3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ls4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ls5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(t40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(ls6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ls7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(t6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(t35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(SelecaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SelecaoAno, 0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelecaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelecaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ls1)
                    .addComponent(ls2)
                    .addComponent(ls3)
                    .addComponent(ls4)
                    .addComponent(ls6)
                    .addComponent(ls5)
                    .addComponent(ls7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t35)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t42, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t34)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t41, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t40, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t39, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t38, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t37, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t36, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        VoltarDataInicial.setText("jButton1");
        VoltarDataInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VoltarDataInicialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VoltarDataInicialMouseExited(evt);
            }
        });
        VoltarDataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarDataInicialActionPerformed(evt);
            }
        });

        AnoPagina1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AnoPagina1.setText("jLabel1");

        AnoPagina2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AnoPagina2.setText("jLabel2");

        SemanaPagina1.setText("jLabel1");

        DiaPagina1.setText("jLabel2");

        MesPagina1.setText("jLabel3");

        SemanaPagina2.setText("jLabel1");

        DiaPagina2.setText("jLabel2");

        MesPagina2.setText("jLabel3");

        jLayeredPane1.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(VoltarDataInicial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AnoPagina1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AnoPagina2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(SemanaPagina1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DiaPagina1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(MesPagina1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(SemanaPagina2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DiaPagina2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(MesPagina2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(AnoPagina1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(AnoPagina2)
                .addGap(292, 292, 292))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(VoltarDataInicial))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(SemanaPagina1))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DiaPagina1)
                            .addComponent(MesPagina1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SemanaPagina2)
                    .addComponent(DiaPagina2)
                    .addComponent(MesPagina2))
                .addGap(280, 280, 280))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(DiaPagina1)
                        .addGap(26, 26, 26)
                        .addComponent(MesPagina1))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(VoltarDataInicial)
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnoPagina1)
                            .addComponent(AnoPagina2))
                        .addGap(73, 73, 73)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SemanaPagina1)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(SemanaPagina2)
                                .addGap(19, 19, 19)
                                .addComponent(DiaPagina2)
                                .addGap(26, 26, 26)
                                .addComponent(MesPagina2))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        setBounds(0, 0, 1050, 534);
    }// </editor-fold>//GEN-END:initComponents

    private void SelecaoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecaoAnoActionPerformed
        try {
            int x = Integer.parseInt(SelecaoAno.getSelectedItem().toString());
            DiaAltera = DiaFIXO;
            CALENDARIO();
            AnoPagina1.setText(SelecaoAno.getSelectedItem().toString()); //altera o ano que esta na pagina quando a pessoa escolhe o ano
            AnoPagina2.setText(SelecaoAno.getSelectedItem().toString());
        } catch (Exception e) {
            SelecaoAno.setSelectedItem(AnoFIXO); //se caso digitar errado, cai no exception e volta ao ano vigente
        }
    }//GEN-LAST:event_SelecaoAnoActionPerformed

    private void SelecaoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecaoMesActionPerformed
        DiaAltera = DiaFIXO; //seleciona o mes pelo jcomboBox
        CALENDARIO();
    }//GEN-LAST:event_SelecaoMesActionPerformed

    private void VoltarDataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarDataInicialActionPerformed
        INICIACALENDARIO();
        CALENDARIO();
        
    }//GEN-LAST:event_VoltarDataInicialActionPerformed

    private void VoltarDataInicialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarDataInicialMouseEntered
        VoltarDataInicial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)); //fazer uma borda com relevo quando passar o mouse
    }//GEN-LAST:event_VoltarDataInicialMouseEntered

    private void VoltarDataInicialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarDataInicialMouseExited
        VoltarDataInicial.setBorder(null);
    }//GEN-LAST:event_VoltarDataInicialMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnoPagina1;
    private javax.swing.JLabel AnoPagina2;
    private javax.swing.JLabel DiaPagina1;
    private javax.swing.JLabel DiaPagina2;
    private javax.swing.JLabel MesPagina1;
    private javax.swing.JLabel MesPagina2;
    private javax.swing.JComboBox SelecaoAno;
    private javax.swing.JComboBox<String> SelecaoMes;
    private javax.swing.JLabel SemanaPagina1;
    private javax.swing.JLabel SemanaPagina2;
    private javax.swing.JButton VoltarDataInicial;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel ls1;
    private javax.swing.JLabel ls2;
    private javax.swing.JLabel ls3;
    private javax.swing.JLabel ls4;
    private javax.swing.JLabel ls5;
    private javax.swing.JLabel ls6;
    private javax.swing.JLabel ls7;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t10;
    private javax.swing.JLabel t11;
    private javax.swing.JLabel t12;
    private javax.swing.JLabel t13;
    private javax.swing.JLabel t14;
    private javax.swing.JLabel t15;
    private javax.swing.JLabel t16;
    private javax.swing.JLabel t17;
    private javax.swing.JLabel t18;
    private javax.swing.JLabel t19;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t20;
    private javax.swing.JLabel t21;
    private javax.swing.JLabel t22;
    private javax.swing.JLabel t23;
    private javax.swing.JLabel t24;
    private javax.swing.JLabel t25;
    private javax.swing.JLabel t26;
    private javax.swing.JLabel t27;
    private javax.swing.JLabel t28;
    private javax.swing.JLabel t29;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t30;
    private javax.swing.JLabel t31;
    private javax.swing.JLabel t32;
    private javax.swing.JLabel t33;
    private javax.swing.JLabel t34;
    private javax.swing.JLabel t35;
    private javax.swing.JLabel t36;
    private javax.swing.JLabel t37;
    private javax.swing.JLabel t38;
    private javax.swing.JLabel t39;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t40;
    private javax.swing.JLabel t41;
    private javax.swing.JLabel t42;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JLabel t9;
    // End of variables declaration//GEN-END:variables

//construçao do calendario
    public void INICIACALENDARIO() { //alteração do formato para data
        SimpleDateFormat Ano = new SimpleDateFormat("yyyy");
        SimpleDateFormat Mes = new SimpleDateFormat("MM");
        SimpleDateFormat Dia = new SimpleDateFormat("dd");
        
        AnoFIXO = Integer.parseInt(Ano.format(new Date()));
        MesFIXO = Integer.parseInt(Mes.format(new Date()));
        DiaFIXO = Integer.parseInt(Dia.format(new Date()));
        
        //JOptionPane.showMessageDialog(null, DiaFIXO + "/" + MesFIXO + "/" + AnoFIXO);

        int AnoMaximo = AnoFIXO + 6; //a soma do valor de 2020 + ano atual + 5anos
        for (int i=2020; i < AnoMaximo; i++) {
            SelecaoAno.addItem(i);
        }
        
        SelecaoAno.setSelectedItem(AnoFIXO);
        
       if (MesFIXO == 1) { //se caso selecionar o mes vigente, assume pelo jframe
            SelecaoMes.setSelectedIndex(0);
        } else if (MesFIXO == 2) {
            SelecaoMes.setSelectedIndex(1);
        } else if (MesFIXO == 3) {
            SelecaoMes.setSelectedIndex(2);
        } else if (MesFIXO == 4) {
            SelecaoMes.setSelectedIndex(3);
        } else if (MesFIXO == 5) {
            SelecaoMes.setSelectedIndex(4);
        } else if (MesFIXO == 6) {
            SelecaoMes.setSelectedIndex(5);
        } else if (MesFIXO == 7) {
            SelecaoMes.setSelectedIndex(6);
        } else if (MesFIXO == 8) {
            SelecaoMes.setSelectedIndex(7);
        } else if (MesFIXO == 9) {
            SelecaoMes.setSelectedIndex(8);
        } else if (MesFIXO == 10) {
            SelecaoMes.setSelectedIndex(9);
        } else if (MesFIXO == 11) {
            SelecaoMes.setSelectedIndex(10);
        } else if (MesFIXO == 12) {
            SelecaoMes.setSelectedIndex(11);
        }
       
 }
        
public void CALENDARIO() {
        t1.setText("");
        t10.setText("");
        t11.setText("");
        t12.setText("");
        t13.setText("");
        t14.setText("");
        t15.setText("");
        t16.setText("");
        t17.setText("");
        t18.setText("");
        t19.setText("");
        t2.setText("");
        t20.setText("");
        t21.setText("");
        t22.setText("");
        t23.setText("");
        t24.setText("");
        t25.setText("");
        t26.setText("");
        t27.setText("");
        t28.setText("");
        t29.setText("");
        t3.setText("");
        t30.setText("");
        t31.setText("");
        t32.setText("");
        t33.setText("");
        t34.setText("");
        t35.setText("");
        t36.setText("");
        t37.setText("");
        t38.setText("");
        t39.setText("");
        t4.setText("");
        t40.setText("");
        t41.setText("");
        t42.setText("");
        t5.setText("");
        t6.setText("");
        t7.setText("");
        t8.setText("");
        t9.setText("");
        
        DiaAltera = DiaFIXO;
        MesAltera = SelecaoMes.getSelectedIndex(); //é utilizado para obter o índice do item selecionado nes que caso, o mes
        AnoAltera = Integer.parseInt(SelecaoAno.getSelectedItem().toString());
        
        int TotalDiaMes = 0; //selecionar os dias do mes vigente
        if (MesAltera == 0) {
            TotalDiaMes = 31;
        } else if (MesAltera == 1) {
            int resultado = (AnoAltera % 4);
            if (resultado == 0) {
                TotalDiaMes = 29; //Ano Bissexto
            } else {
                TotalDiaMes = 28; //Ano nao Bissexto
            }
        } else if (MesAltera == 2 ) {
            TotalDiaMes = 31;
        } else if (MesAltera == 3 ) {
            TotalDiaMes = 30;
        } else if (MesAltera == 4 ) {
            TotalDiaMes = 31;
        } else if (MesAltera == 5 ) {
            TotalDiaMes = 30;
        } else if (MesAltera == 6 ) {
            TotalDiaMes = 31;
        } else if (MesAltera == 7 ) {
            TotalDiaMes = 31;
        } else if (MesAltera == 8 ) {
            TotalDiaMes = 30;
        } else if (MesAltera == 9 ) {
            TotalDiaMes = 31;
        } else if (MesAltera == 10 ) {
            TotalDiaMes = 30;
        } else if (MesAltera == 11 ) {
            TotalDiaMes = 31;
        }
    
        Calendar calendar = Calendar.getInstance(); //intancia o calendario e converte no dia do mes se desejar
        calendar.set(AnoAltera, MesAltera, 1);
        int SetaDia = 0;

        int Semana = calendar.get(Calendar.DAY_OF_WEEK); //escolhi dias da semana para apresentar no formulario
        if (Semana == Calendar.SUNDAY) {
            SetaDia = 1; //Dom
        } else if (Semana == Calendar.MONDAY) {
            SetaDia = 2; //Seg
        } else if (Semana == Calendar.TUESDAY) {
            SetaDia = 3; //Ter
        } else if (Semana == Calendar.WEDNESDAY) {
            SetaDia = 4; //Qua
        } else if (Semana == Calendar.THURSDAY) {
            SetaDia = 4; //Qui
        } else if (Semana == Calendar.FRIDAY) {
            SetaDia = 5; //Sex
        } else if (Semana == Calendar.SATURDAY) {
            SetaDia = 6; //Sab
        }

        
        for(int i=1; i<=TotalDiaMes; i++) {// Laço de repetiçao para preenche os dias do mes vigente
        switch (SetaDia) {
            case 1:
                t1.setText("" + i);
                break;
            case 2:
                t2.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) { //sublinhar de vermelho o dia vigente
                    t2.setForeground(Color.red);
                } else {
                    t2.setForeground(Color.black);
                }
                break;
            case 3:
                t3.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t3.setForeground(Color.red);
                } else {
                    t3.setForeground(Color.black);
                }
                break;
            case 4:
                t4.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t4.setForeground(Color.red);
                } else {
                    t4.setForeground(Color.black);
                }
                break;
            case 5:
                t5.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t5.setForeground(Color.red);
                } else {
                    t5.setForeground(Color.black);
                }
                break;
            case 6:
                t6.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t6.setForeground(Color.red);
                } else {
                    t6.setForeground(Color.black);
                }
                break;
            case 7:
                t7.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t7.setForeground(Color.red);
                } else {
                    t7.setForeground(Color.black);
                }
                break;
            case 8:
                t8.setText("" + i);
                break;
            case 9:
                t9.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t9.setForeground(Color.red);
                } else {
                    t9.setForeground(Color.black);
                }
                break;
            case 10:
                t10.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t10.setForeground(Color.red);
                } else {
                    t10.setForeground(Color.black);
                }
                break;
            case 11:
                t11.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t11.setForeground(Color.red);
                } else {
                    t11.setForeground(Color.black);
                }
                break;
            case 12:
                t12.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t12.setForeground(Color.red);
                } else {
                    t12.setForeground(Color.black);
                }
                break;
            case 13:
                t13.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t13.setForeground(Color.red);
                } else {
                    t13.setForeground(Color.black);
                }
                break;
            case 14:
                t14.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t14.setForeground(Color.red);
                } else {
                    t14.setForeground(Color.black);
                }
                break;
            case 15:
                t15.setText("" + i);
                break;
            case 16:
                t16.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t16.setForeground(Color.red);
                } else {
                    t16.setForeground(Color.black);
                }
                break;
            case 17:
                t17.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t17.setForeground(Color.red);
                } else {
                    t17.setForeground(Color.black);
                }
                break;
            case 18:
                t18.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t18.setForeground(Color.red);
                } else {
                    t18.setForeground(Color.black);
                }
                break;
            case 19:
                t19.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t19.setForeground(Color.red);
                } else {
                    t19.setForeground(Color.black);
                }
                break;
            case 20:    
               t20.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t20.setForeground(Color.red);
                } else {
                    t20.setForeground(Color.black);
                }
                break;
            case 21:
                t21.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t21.setForeground(Color.red);
                } else {
                    t21.setForeground(Color.black);
                }
                break;
            case 22:
                t22.setText("" + i);
                break;
            case 23:
                t23.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t23.setForeground(Color.red);
                } else {
                    t23.setForeground(Color.black);
                }
                break;
            case 24:
                t24.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t24.setForeground(Color.red);
                } else {
                    t24.setForeground(Color.black);
                }
                break;
            case 25:
                t25.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t25.setForeground(Color.red);
                } else {
                    t25.setForeground(Color.black);
                }    
                break;
            case 26:
                t26.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t26.setForeground(Color.red);
                } else {
                    t26.setForeground(Color.black);
                } 
                break;
            case 27:
                t27.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t27.setForeground(Color.red);
                } else {
                    t27.setForeground(Color.black);
                } 
                break;
            case 28:
                t28.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t28.setForeground(Color.red);
                } else {
                    t28.setForeground(Color.black);
                } 
                break;
            case 29:
                t29.setText("" + i);
                break;
            case 30:
                t30.setText("" + i);
                t30.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t30.setForeground(Color.red);
                } else {
                    t30.setForeground(Color.black);
                }
                break;
            case 31:
                t31.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t31.setForeground(Color.red);
                } else {
                    t31.setForeground(Color.black);
                }
                break;
            case 32:
                t32.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t32.setForeground(Color.red);
                } else {
                    t32.setForeground(Color.black);
                }
                break;
            case 33:
                t33.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t33.setForeground(Color.red);
                } else {
                    t33.setForeground(Color.black);
                }
                break;
            case 34:
                t34.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t34.setForeground(Color.red);
                } else {
                    t34.setForeground(Color.black);
                }
                break;
            case 35:
                t35.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t35.setForeground(Color.red);
                } else {
                    t35.setForeground(Color.black);
                }
                break;
            case 36:
                t36.setText("" + i);
                break;
            case 37:
                t37.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t37.setForeground(Color.red);
                } else {
                    t37.setForeground(Color.black);
                }
                break;
            case 38:
                t38.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t38.setForeground(Color.red);
                } else {
                    t38.setForeground(Color.black);
                }
                break;
            case 39:
                t39.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t39.setForeground(Color.red);
                } else {
                    t39.setForeground(Color.black);
                }
                break;
            case 40:
                t40.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t40.setForeground(Color.red);
                } else {
                    t40.setForeground(Color.black);
                }
                break;
            case 41:
                t41.setText("" + i);
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t41.setForeground(Color.red);
                } else {
                    t41.setForeground(Color.black);
                }
                break;
            case 42:
                if (i == DiaFIXO & MesAltera == MesFIXO - 1 & AnoAltera == AnoFIXO) {
                    t42.setForeground(Color.red);
                } else {
                    t42.setForeground(Color.black);
                }
                t42.setText("" + i);
                break;
                
            }  
        SetaDia++;
        }
    }
}