package PRINCIPAL;

import AGENDAMENTO.AGENDAMENTO;
import UTILIDA.CONEXAO;
import UTILIDA.GRA_ALT_EXC;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrezza
 */
public class SERVICO extends javax.swing.JDialog {
    CONEXAO CONEXAO = new CONEXAO();
    int grava = 0;
    
    /**
     * Creates new form SERVICO
     */
    public SERVICO(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        CONEXAO.conecta();
        PREENCHE_TABELA();
        BotaoSalvar.setToolTipText("Salvar serviço");
        BotaoNovoServico.setToolTipText("Novo serviço");
        BotaoExcluir.setToolTipText("Excluir serviço");
        BotaoExcluir.setVisible(false);
        Cod.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Camadas = new javax.swing.JLayeredPane();
        BotaoNovoServico = new javax.swing.JButton();
        BotaoSalvar = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();
        nomeservico = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        jScrollPaneTabela = new javax.swing.JScrollPane();
        TabelaServico = new javax.swing.JTable();
        Lservico = new javax.swing.JLabel();
        Lvalor = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Cod = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Camadas.setBackground(new java.awt.Color(255, 255, 255));
        Camadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Camadas.setAlignmentX(0.1F);
        Camadas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Camadas.setOpaque(true);

        BotaoNovoServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/livro.png"))); // NOI18N
        BotaoNovoServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoNovoServicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoNovoServicoMouseExited(evt);
            }
        });
        BotaoNovoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoServicoActionPerformed(evt);
            }
        });
        Camadas.add(BotaoNovoServico);
        BotaoNovoServico.setBounds(10, 10, 50, 50);

        BotaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/salvar.png"))); // NOI18N
        BotaoSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoSalvarMouseExited(evt);
            }
        });
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
        Camadas.add(BotaoSalvar);
        BotaoSalvar.setBounds(70, 10, 50, 50);

        BotaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/deleta.png"))); // NOI18N
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });
        Camadas.add(BotaoExcluir);
        BotaoExcluir.setBounds(360, 10, 50, 50);

        nomeservico.setBorder(null);
        nomeservico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeservicoFocusGained(evt);
            }
        });
        Camadas.add(nomeservico);
        nomeservico.setBounds(60, 90, 350, 20);

        valor.setBorder(null);
        valor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorFocusGained(evt);
            }
        });
        Camadas.add(valor);
        valor.setBounds(50, 120, 70, 20);

        TabelaServico.setAutoCreateRowSorter(true);
        TabelaServico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TabelaServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Serviço", "Valor"
            }
        ));
        TabelaServico.setGridColor(new java.awt.Color(0, 0, 0));
        TabelaServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaServicoMouseClicked(evt);
            }
        });
        jScrollPaneTabela.setViewportView(TabelaServico);

        Camadas.add(jScrollPaneTabela);
        jScrollPaneTabela.setBounds(10, 160, 400, 90);

        Lservico.setText("Serviço:");
        Camadas.add(Lservico);
        Lservico.setBounds(10, 90, 50, 20);

        Lvalor.setText("Valor:");
        Camadas.add(Lvalor);
        Lvalor.setBounds(10, 120, 40, 20);
        Camadas.add(jSeparator2);
        jSeparator2.setBounds(10, 110, 400, 10);
        Camadas.add(jSeparator3);
        jSeparator3.setBounds(10, 140, 110, 10);

        Cod.setText("Cod");
        Camadas.add(Cod);
        Cod.setBounds(380, 140, 30, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/logo.png"))); // NOI18N
        Camadas.add(jLabel1);
        jLabel1.setBounds(160, 10, 110, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Camadas, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Camadas, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoNovoServicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoNovoServicoMouseEntered

    }//GEN-LAST:event_BotaoNovoServicoMouseEntered

    private void BotaoNovoServicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoNovoServicoMouseExited

    }//GEN-LAST:event_BotaoNovoServicoMouseExited

    private void BotaoNovoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoServicoActionPerformed
        try {
            BotaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/salvar.png")));
            BotaoSalvar.setToolTipText("Salvar serviço");
            grava = 0;
            BotaoExcluir.setVisible(false);
            Limpa();
        } catch (Exception err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_BotaoNovoServicoActionPerformed

    private void BotaoSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSalvarMouseEntered

    }//GEN-LAST:event_BotaoSalvarMouseEntered

    private void BotaoSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSalvarMouseExited

    }//GEN-LAST:event_BotaoSalvarMouseExited

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        try {
            if(grava == 0) {
                int cont = nomeservico.getText().length();
                double valorser = Double.parseDouble(valor.getText());
                if(cont > 0) {
                    gravar();
                    Limpa();
                    PREENCHE_TABELA();
                }
            } else {
                Alteracao();
                PREENCHE_TABELA();
            }

        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Erro! Substitua a virgula por ponto.");
        
        valor.setText("0");
        System.out.println(err);
    }     
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirActionPerformed
        try {
            int opcao = JOptionPane.showConfirmDialog(null, "Deseja excluir?");
            if(opcao == JOptionPane.YES_NO_OPTION) {
                Excluir();
                PREENCHE_TABELA();
                Limpa();
            }
        } catch (Exception err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_BotaoExcluirActionPerformed

    private void nomeservicoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeservicoFocusGained

    }//GEN-LAST:event_nomeservicoFocusGained

    private void valorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorFocusGained

    }//GEN-LAST:event_valorFocusGained

    private void TabelaServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaServicoMouseClicked
        try {
            MOSTRA_DADOS_TABELA();
            BotaoExcluir.setVisible(true);
            grava = 1;
            BotaoSalvar.setToolTipText("Salvar alterações");
            BotaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/salvar.png")));

        } catch (Exception err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_TabelaServicoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SERVICO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SERVICO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SERVICO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SERVICO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SERVICO dialog = new SERVICO(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoNovoServico;
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JLayeredPane Camadas;
    private javax.swing.JLabel Cod;
    private javax.swing.JLabel Lservico;
    private javax.swing.JLabel Lvalor;
    private javax.swing.JTable TabelaServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPaneTabela;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nomeservico;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables

private PRINCIPAL ECRAPRIN;
    public void MostraServico(PRINCIPAL MostraServico) {
        this.ECRAPRIN = MostraServico;
        setVisible(true);
    }
private AGENDAMENTO AGENDAMEN;

public void MostraServico(AGENDAMENTO MostraServico){
        this.AGENDAMEN = MostraServico;
        setVisible(true);
    }
    
public void gravar() throws IOException {
        String[] coluna = {"nomeservico", "valor"};
        String[] v = {nomeservico.getText(), valor.getText()};
        
        String tabela = "servico";
        String Mensagem = "Concluido";
        GRA_ALT_EXC gravacao = new GRA_ALT_EXC();
        gravacao.GRAVA(coluna, v, tabela, Mensagem);

    }

public void Alteracao() throws IOException {
        try {
            int x = Integer.parseInt(Cod.getText());
            String[] coluna = {"nomeservico", "valor"};
            String[] v = {nomeservico.getText(), valor.getText()};

            String tabela = "servico";
            String condicao = " WHERE cod = " + Cod.getText();
            GRA_ALT_EXC altera = new GRA_ALT_EXC();
            altera.ALTERA(coluna, v, tabela, condicao);

        } catch (Exception err) {
                System.out.println(err);
        }
}

public void Excluir() throws IOException {
        try {
            int x = Integer.parseInt(Cod.getText());
            String tabela = "servico";
            String condicao = " WHERE cod = " + Cod.getText();
            GRA_ALT_EXC exclui = new GRA_ALT_EXC();
            exclui.EXCLUIR(tabela, condicao); 
        } catch (Exception err) {
            System.out.println(err);
        }
}

public void PREENCHE_TABELA() {
    
    TabelaServico.getColumnModel().getColumn(0).setPreferredWidth(650);
    TabelaServico.getColumnModel().getColumn(1).setPreferredWidth(350);
    
    DefaultTableModel modelo = (DefaultTableModel) TabelaServico.getModel();
    modelo.setNumRows(0);
    
    try {
        CONEXAO.executaSQL("select * from servico order by nomeservico");
        while (CONEXAO.resultset.next()) {
            modelo.addRow(new Object[]{CONEXAO.resultset.getString("nomeservico"),
                        "€ " + CONEXAO.resultset.getString("valor"),
                        });
        }
    } catch (SQLException erro) {
        
    }
}

public void Limpa() {
    Cod.setText("");
    nomeservico.setText("");
    valor.setText("");  
    }

public void MOSTRA_DADOS_TABELA() {
        try {
            int Linha = TabelaServico.getSelectedRow();
            CONEXAO.executaSQL("select * from servico order by nomeservico LIMIT " + Linha + " , 1 ");
            CONEXAO.resultset.first();
            Cod.setText(CONEXAO.resultset.getString("cod"));
            nomeservico.setText(CONEXAO.resultset.getString("nomeservico"));
            valor.setText(CONEXAO.resultset.getString("valor"));
            
        } catch (SQLException erro) {
//        JOptionPane.showMessageDialog(null, "Erro" + erro);
        }
    }

}
