package LOGIN;

import PRINCIPAL.PRINCIPAL;
import UTILIDA.CLIBANCO;
import UTILIDA.CLICPTOGRAFIA;
import UTILIDA.CONEXAO;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Andrezza
 */
public class LOGIN extends javax.swing.JFrame {
        CONEXAO ConLogin;
        CLIBANCO criabanco;
        String CRIPTOGRAFADO;
    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
        ConLogin = new CONEXAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        CamadaPass = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TPass = new javax.swing.JPasswordField();
        TLogin = new javax.swing.JTextField();
        PAPELDEPAREDE = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Password:");
        CamadaPass.add(jLabel2);
        jLabel2.setBounds(10, 50, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Login:");
        CamadaPass.add(jLabel3);
        jLabel3.setBounds(10, 10, 45, 30);

        TPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPassActionPerformed(evt);
            }
        });
        CamadaPass.add(TPass);
        TPass.setBounds(80, 50, 110, 30);

        TLogin.setText("SMART");
        TLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TLoginActionPerformed(evt);
            }
        });
        CamadaPass.add(TLogin);
        TLogin.setBounds(60, 10, 130, 30);

        jLayeredPane1.add(CamadaPass);
        CamadaPass.setBounds(240, 10, 190, 90);

        PAPELDEPAREDE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/smartlevel_logo-06 (1).png"))); // NOI18N
        jLayeredPane1.add(PAPELDEPAREDE);
        PAPELDEPAREDE.setBounds(0, 10, 280, 170);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(270, 110, 70, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton2);
        jButton2.setBounds(360, 110, 73, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TLoginActionPerformed

    private void TPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPassActionPerformed
        CLICPTOGRAFIA criptogr = new CLICPTOGRAFIA();
        String pass = String.valueOf(TPass.getPassword());
        criptogr.InicialCliptografia(pass);
        CRIPTOGRAFADO = (criptogr.TEXTOCLIPTOGRAFADO);
            try {
                Login();
            } catch (IOException ex) {
                Logger.getLogger(LOGIN.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_TPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try {
                CLICPTOGRAFIA criptogr = new CLICPTOGRAFIA();
                String pass = String.valueOf(TPass.getPassword());
                criptogr.InicialCliptografia(pass);
                CRIPTOGRAFADO = (criptogr.TEXTOCLIPTOGRAFADO);
                Login();
            } catch (IOException ex) {
                Logger.getLogger(LOGIN.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane CamadaPass;
    private javax.swing.JLabel PAPELDEPAREDE;
    private javax.swing.JTextField TLogin;
    private javax.swing.JPasswordField TPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables

public void Login() throws IOException {
        ConLogin = new CONEXAO();
        ConLogin.conecta();
        try {
            String pass = CRIPTOGRAFADO;
            String login = (String) TLogin.getText();
            String sql = "select * from login Where login = '" + login + "'" + " and pass = '" + pass + "'";
            ConLogin.executaSQL(sql);
            ConLogin.resultset.first();

            if (pass.equals(ConLogin.resultset.getString("pass"))
                    && login.equals(ConLogin.resultset.getString("login"))) {
                new PRINCIPAL().setVisible(true);
                ConLogin.desconecta();
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "NAO PERMITIDO", "ERRO", (0));
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "NAO PERMITIDO", "ERRO", (0));
        }
        ConLogin.desconecta();
    }
}

